name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        bash bootstrap.sh
        ls /app/shared
        docker build . --file Dockerfile --tag asuka109/fe:$(date +%s)
