name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        bash bootstrap.sh
        docker build . --file Dockerfile --tag asuka109/fe:$(date +%s)
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: asuka109
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Deploy to Docker Hub
      run: |
        docker push asuka109/fe
