name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        bash bootstrap.sh
    - name: Debuggging with tmate
      # You may pin to the exact commit or the version.
      # uses: GitHub30/action-tmate@9efd9f8435a9057bb1571c4b146e130bc12506d7
      uses: GitHub30/action-tmate@master
